eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


services:
  orderService:
    uri: http://ORDER-SERVICE/order/bookOrder
  paymentService:
    uri: http://PAYMENT-SERVICE/payment/doPayment

    
    
